# Generated by Django 4.2.20 on 2025-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'libros_autores',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'managed': False, 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'managed': False, 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='cicloescolar',
            options={'managed': False, 'verbose_name_plural': 'Ciclos Escolares'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'managed': False, 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'managed': False, 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'managed': False, 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': False, 'verbose_name_plural': 'Préstamos'},
        ),
    ]
