# Generated by Django 4.2.20 on 2025-04-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libroautor_alter_alumno_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
        migrations.AlterModelTable(
            name='autor',
            table='autores',
        ),
        migrations.AlterModelTable(
            name='cicloescolar',
            table='ciclos_escolares',
        ),
        migrations.AlterModelTable(
            name='editorial',
            table='editoriales',
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='especialidades',
        ),
        migrations.AlterModelTable(
            name='libro',
            table='libros',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='prestamos',
        ),
    ]
