# Generated by Django 4.2.21 on 2025-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('codigo_pieza', models.CharField(max_length=8)),
                ('codigo_fabricante', models.CharField(max_length=3)),
                ('descripcion', models.TextField()),
                ('programa_cad', models.CharField(blank=True, max_length=150, null=True)),
                ('material', models.CharField(choices=[('AL', 'Aluminio'), ('AC', 'Acero'), ('PL', 'Plástico')], max_length=2)),
            ],
        ),
    ]
