# Generated by Django 4.2.21 on 2025-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_piezas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id_motor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('num_piezas', models.IntegerField()),
                ('programa_cad', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('Motocicleta', 'Motocicleta'), ('Automóvil', 'Automóvil')], max_length=12)),
                ('caballos_fuerza', models.IntegerField(blank=True, null=True)),
                ('tipo_refrigeracion', models.CharField(blank=True, max_length=50, null=True)),
                ('potencia_fiscal', models.IntegerField(blank=True, null=True)),
                ('tipo_anclaje', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
