# Generated by Django 4.2.21 on 2025-06-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_piezas', '0002_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id_operario', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
