version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - POSTGRES_DB=biblioteca_cendi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PYTHONUNBUFFERED=1  # Ver todo el output
    depends_on:
      - db
    networks:
      - app-network
    command: >
      bash -c "
        python /app/manage.py makemigrations &&
        python /app/manage.py migrate &&
        python /app/crear_ciclo.py &&
        python /app/manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./esquema_biblioteca_cendi.sql:/docker-entrypoint-initdb.d/esquema_biblioteca_cendi.sql
    environment:
      - POSTGRES_DB=biblioteca_cendi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: